version: 2
jobs:
  build:

    working_directory: ~/company-service

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          key: company-service-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: company-service-{{ checksum "pom.xml" }}

      - run: mvn clean verify install

      - store_test_results:
          path: target/failsafe-reports